### PR TITLE
feat: cli option to not encode/decode default values

### LINKED ISSUE #43: Handling of default values do not conform with proto3 language guide
Proto3 language guide [states](https://developers.google.com/protocol-buffers/docs/proto3#default):

> When a message is parsed, if the encoded message does not contain a particular singular element, the corresponding field in the parsed object is set to the default value for that field.

Looking at `protons`'s code and behaviour, it is clear that:

- Fields are always encoded in the message, even if their value is the default one (expected: do not encode the field).
- When decoding a message and a field is not present, it is set as `undefined` (expected: set to the default value of the field).

Default values are type-specific:

> - For strings, the default value is the empty string.
> - For bytes, the default value is empty bytes.
> - For bools, the default value is false.
> - For numeric types, the default value is zero.
> - For [enums](https://developers.google.com/protocol-buffers/docs/proto3#enum), the default value is the first defined enum value, which must be 0.
> - For message fields, the field is not set. Its exact value is language-dependent. See the [generated code guide](https://developers.google.com/protocol-buffers/docs/reference/overview) for details.

I see that the tests are done against [pbjs](https://github.com/ipfs/protons/blob/676c01dae7ff5b4d3985113573079ba605d83ef6/packages/protons/test/index.spec.ts#L43), this package [states](https://www.npmjs.com/package/pbjs):

> Unlike other JavaScript implementations, this library doesn't write out default values.

Is the choice to not follow the proto3 language guide regarding default value on purpose in `protons`?

Keen to open a PR, I can see two ways forward:

1. Follow proto3 language guide: do not encode a field when it's set to a default value, set a default value when a field is absent as decoding
2. Enabling some way to parameterized this behaviour (guidance would be welcome here).

### PR DESCRIPTION
**Pull request by D4nte**
Resolves #43

### CODE REVIEW

**Comment by D4nte** [comment]
Draft until #46 is merged as both PR modify the CLI flag handling.

**Comment by D4nte** [comment]
@achingbrain this is now rebased and ready to go. lmk your thoughts.

**Comment by BigLep** [comment]
2022-09-02 triage note:  posted notes and next steps in the issue: https://github.com/ipfs/protons/issues/43

**Comment by fryorcraken** [comment]
This should help : https://buf.build/blog/protobuf-language-specification

**Comment by BigLep** [comment]
2022-10-07 triage note: @achingbrain will open a followup PR to address #43

**Pull request closed without merging**
